compilers=&exo_0_2_1

defaultCompiler=exocc
supportsBinary=false
compilerType=exo
instructionSet=llvm

group.exo_0_2_1.compilers=exocc
compiler.exocc.exe=/home/fricke/.local/bin/exocc
compiler.exocc.name=exocc
